### PR TITLE
Changes for IVS

### PR DESCRIPTION
**Pull request by anadon**
Here are a number of changes prepared for our usage at Michigan Tech.  I'd be happy to have a second opinion.

### CODE REVIEW

**Comment by tfhartmann** [comment]
@FASRC You guys might want to coordinate this module with the HMS RC Fork as well  (https://github.com/hmsrc/puppet-slurm)

**Comment by jfmcdonald** [comment]
@anadon you may want to pull your own fork from FASRC to incorporate your changes.

**Comment by anadon** [comment]
Should I set upstream to https://github.com/fasrc/puppet-slurm/ ?

**Comment by jfmcdonald** [comment]
best would be for you pull your own fork into your org and make your site specific changes there.

**Comment by anadon** [comment]
Upsteam merged all your changes and my changes.  You may want to rebase so you don't diverge too far.

**Pull request closed without merging**
